# Generated by Django 6.0.5 on 2026-07-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_employee_date_joined_employee_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.tariffplan'),
        ),
    ]
