# Generated by Django 6.0.2 on 2026-02-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
