# Generated by Django 5.0.6 on 2026-03-13 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_role_alter_sale_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(auto_now_add=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('qty_in', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_left', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.batch'),
        ),
    ]
