# Generated by Django 5.0.6 on 2026-03-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sale_options_alter_sale_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_left',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
