# Generated by Django 6.0 on 2026-04-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='branch',
        ),
    ]
