# Generated by Django 6.0 on 2026-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_expense_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='score',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
