# Generated by Django 6.0 on 2026-05-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customer_score_sale_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name="O'lchov birligi nomi")),
                ('short_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Qisqartma nomi')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='unity',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.unit'),
        ),
    ]
