# Generated by Django 6.0.5 on 2026-05-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
