# Generated by Django 6.0.5 on 2026-05-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customer_total_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
