# Generated by Django 6.0.5 on 2026-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_employee_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
