# Generated by Django 6.0.5 on 2026-06-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_supplier_debt_supplier_total_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='boss_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Boshliq ismi'),
        ),
    ]
