# Generated by Django 6.0.5 on 2026-06-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_supplier_address_supplier_boss_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('supplier', "Ta'minotchi"), ('product', 'Mahsulot'), ('category', 'Kategoriya'), ('employee', 'Xodim')], max_length=50, verbose_name='Tur')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('status', models.CharField(default="O'chirilgan", max_length=50, verbose_name='Status')),
                ('original_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
