# Generated by Django 6.0.5 on 2026-06-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_archiveditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveditem',
            name='item_type',
            field=models.CharField(choices=[('supplier', "Ta'minotchi"), ('product', 'Mahsulot'), ('category', 'Kategoriya'), ('employee', 'Xodim'), ('customer', 'Mijoz'), ('role', 'Rol')], max_length=50, verbose_name='Tur'),
        ),
    ]
