# Generated by Django 6.0.5 on 2026-06-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_archiveditem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi")),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('click', 'Click')], default='cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_debt_payments', to='api.customer')),
            ],
        ),
    ]
