# Generated by Django 6.0.5 on 2026-06-10 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_customerpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sahifa nomi')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Tizim uchun qisqa nomi')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, verbose_name="Ko'rish")),
                ('can_create', models.BooleanField(default=False, verbose_name='Yaratish')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Tahrirlash')),
                ('can_delete', models.BooleanField(default=False, verbose_name="O'chirish")),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to='api.apppage')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.role')),
            ],
            options={
                'unique_together': {('role', 'page')},
            },
        ),
    ]
