# Generated by Django 6.0.5 on 2026-06-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_activitylog_company_apppage_company_and_more'),
        ('organization', '0002_employee_date_joined_employee_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, verbose_name="O'lchov birligi nomi"),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('company', 'name')},
        ),
    ]
